# Generated by Django 4.0.2 on 2022-02-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sinf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.sinflar'),
        ),
    ]
