# Generated by Django 4.0.2 on 2022-02-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.mavzular')),
            ],
            options={
                'verbose_name': 'Amaliy mashq',
                'verbose_name_plural': 'Amaliy mashqlar',
            },
        ),
        migrations.CreateModel(
            name='Amaliyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.mavzular')),
            ],
            options={
                'verbose_name': 'Maruza dars',
                'verbose_name_plural': 'Maruza darslar',
            },
        ),
    ]
